  
name: Docker CD Tag

on:
  push:
    tags:
      - '*'

jobs:

  deploy-gateway:

    name: Deploy Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and Publish Docker Image
        run: |
          docker build . -t zekro/vctr-gw:$RELEASE_VERSION -f ./Gateway/Dockerfile
          docker login -u zekro -p ${{ secrets.DOCKER_PASSWORD }}
          docker push zekro/vctr-gw:$RELEASE_VERSION

